"""Initial migration.

Revision ID: 327edbcb387c
Revises: 24c77d616d80
Create Date: 2024-10-15 16:52:58.134386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327edbcb387c'
down_revision = '24c77d616d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.alter_column('filtered_characters',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.alter_column('filtered_characters',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
